Controllers/FeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetReader.Models;
using WebMatrix.WebData;
using System.ServiceModel.Syndication;
using System.Diagnostics;
using LinqGrouping.Models;
using System.Xml;
using System.Data;
using System.Data.Entity;
using System.Xml.Linq;
using System.Net;
using System.IO;
using System.Text;
using DotNetReader.Utilities;
using PagedList;

namespace DotNetReader.Controllers
{
    [Authorize]
    public class FeedController : Controller
    {
        private ReaderDb _db = new ReaderDb();
        private int userId = WebSecurity.CurrentUserId;

        public ActionResult Index()
        {
            var model = _db.Feeds.Include(f => f.Category)
                        .Where(u => u.UserId == userId);

            return View(model.ToList());
        }


        //
        // GET the list of feeds of the user

        [ChildActionOnly]
        public ActionResult ListFeed()
        {
            // get a FeedListItems collection
            var m = from b in _db.Feeds
                    where b.UserId == userId
                    select new FeedListItems()
                    {
                        Id = b.FeedID,
                        Category = b.Category.Name,
                        Name = b.Name,
                        Stared = b.Events.Count(x => x.Favorite == true),
                        NewItemsCount = b.Events.Count(x => x.Unread == null || x.Unread == true) 
                    };

            // Group the feeds by Category
            var FeedListItem = from b in m
                               group b by b.Category into g
                               select new Group<FeedListItems, String> { Values = g, Key = g.Key };

            return PartialView("_FeedList", FeedListItem.ToList());
        }

        //
        // GET the feed view by id

        [HttpGet]
        public ActionResult View(int id, int? page)
        {

            int pageNumber = (page ?? 1);
            UserProfile up = _db.UserProfiles.Find(userId);
            int feedMaxEvent = (int)up.feedMaxEvent;

            Feed feedInfo = _db.Feeds.Find(id);

            if (feedInfo == null)
            {
                return RedirectToAction("Index");
            }

            if (up.SynchronisationType == (int)SynchroType.Partial) //check if we need to update now
            {
                getLastEvent(feedInfo, feedMaxEvent);
                flushCache(feedInfo, feedMaxEvent);
            }

            ViewBag.FeedTitle = feedInfo.Name;
            ViewBag.id = id;
            IEnumerable<Event> model = null;

            if (up.articleDisplayType == (int)DisplayType.UnreadItems)
            {
             
                model = _db.Events
                        .Where(a => a.FeedID == id && (a.Unread == true || a.Unread == null))
                        .OrderByDescending(o => o.Pubdate)
                        .Take(feedMaxEvent);
            }
            else if (up.articleDisplayType == (int)DisplayType.AllItems)
            {
                model = _db.Events
                        .Where(a => a.FeedID == id)
                        .OrderByDescending(o => o.Pubdate)
                        .Take(feedMaxEvent);
            }
            else
            {
                Redirect("Index");
            }

            return View(model.ToPagedList(pageNumber,(int)up.EventPerPage));
        }

        //
        // GET the feeds articles by subcategory

        public ActionResult Views(string slug, int? page){

            int pageNumber = (page ?? 1);
            List<Event> model = new List<Event>();
            UserProfile up = _db.UserProfiles.Find(userId);
            int feedMaxEvent = (int)up.feedMaxEvent;


            if (slug.Equals("All"))
            {
                var feeds = _db.Feeds.Where(u => u.UserId == userId).ToList();
                foreach (Feed feed in feeds)
                {
                    model.AddRange(_db.Events.Where(e => e.FeedID == feed.FeedID && (e.Unread == true || e.Unread == null)).ToList());
                }


            }
            else if (slug.Equals("Star"))
            {
                var feeds = _db.Feeds.Where(u => u.UserId == userId).ToList();
                foreach (Feed feed in feeds)
                {
                    model.AddRange(_db.Events.Where(e => e.FeedID == feed.FeedID && e.Favorite == true).ToList());
                }

            }

            else{

                RedirectToAction("Index");
             }
            ViewBag.Slug = slug;
            return View("View", model.ToPagedList(pageNumber, (int)up.EventPerPage));
        }


        //
        // Mark all item as read from the feed id

        public ActionResult MarkAllAsRead(int id)
        {
            var events = _db.Events.Where(i => i.FeedID == id).ToList();

            if (events != null)
            {
                events.ForEach(s => s.Unread = false);
                _db.SaveChanges();
            }
            return RedirectToAction("View", new { id = id });
        }


        //
        // Update all the feeds
        // !It might take a while to do it


        [AllowAnonymous]
        public ActionResult UpdateAll(string synchroCode)
        {
            if (WebSecurity.IsAuthenticated)
            {
                var feeds = _db.Feeds.Where(u => u.UserId == userId).ToList();
                int maxEvent = (int)_db.UserProfiles.Where(u => u.UserId == userId).SingleOrDefault().feedMaxEvent;

                foreach (Feed feed in feeds)
                {
                    getLastEvent(feed, maxEvent);
                    flushCache(feed, maxEvent);
                }
                return RedirectToAction("Index", "Home");
            }
            else //Si il est pas authentifié on cherche l'utilisateur par son code de synchro
            // localhost:59034/Feed/UpdateAll/P12UIe0vAJLh9DiuMJGN ex
            {
                UserProfile up = _db.UserProfiles.Where(t => t.SynchroCode == synchroCode).SingleOrDefault();
                if (up != null)
                {
                    if (up.SynchronisationType != (int)SynchroType.Manual)
                    {
                        List<Feed> feeds = _db.Feeds.Where(u => u.UserId == up.UserId).ToList();
                        foreach (Feed feed in feeds)
                        {
                            getLastEvent(feed, (int)up.feedMaxEvent, up.UserId);
                            flushCache(feed, (int)up.feedMaxEvent);
                        }

                        return Content("Update done");
                    }
                    else
                    {
                        return Content("Auto update are disabled");
                    }
                }
                else
                {
                    return Content("Invalid synchro code");
                }
            }
        
        }


        //
        // Delete old articles from the specific feed 

        [ChildActionOnly]
        private void flushCache(Feed feedInfo, int feedMaxEvent)
        {

            //Check if the cache > limit defined by the user
            if (feedInfo.Events.Where(f => f.Favorite == false && f.Unread != true).Count() > feedMaxEvent)
            {
                IEnumerable<Event> Ev = feedInfo.Events
                .Where(f => f.Favorite == false && f.Unread != true)
                .OrderBy(i => i.EventID)
                .TakeWhile(c => feedInfo.Events.Count() > feedMaxEvent);

                foreach (Event e in Ev)
                {
                    _db.Events.Remove(e);
                }
                _db.SaveChanges();
            }

        }

        //
        // GET: /Feed/Create

        public ActionResult Create()
        {
            var cat = _db.Categories.Where(u => u.UserId == userId);
            ViewBag.CategoryList = new SelectList(cat, "CategoryID", "Name");
            return View();
        }

        //
        // POST: /Feed/Create

        [HttpPost]
        public ActionResult Create(AddFeedModel feed)
        {
            if (ModelState.IsValid)
            {

                if (isValidFeed(feed.Url))
                {

                    SyndicationFeed f = SyndicationFeed.Load(System.Xml.XmlReader.Create(feed.Url));

                    Feed Coming = new Feed()
                    {
                        Url = feed.Url,
                        Name = f.Title.Text,
                        Lastupdate = new DateTime(2000, 1, 1),
                        Description = f.Description.Text,
                        Website = f.Links.Count > 0 ? f.Links[0].Uri.OriginalString : "",
                        CategoryID = feed.CategoryID,
                        UserId = userId
                    };

                    _db.Feeds.Add(Coming);
                    _db.SaveChanges();

                    //On recupere les derniers articles pour le flux
                    int feedMaxEvent = (int)_db.UserProfiles.Find(WebSecurity.CurrentUserId).feedMaxEvent;
                    getLastEvent(Coming, feedMaxEvent);

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Error, the feed cannot be read. Sorry");
                }
            }
      
            ViewBag.CategoryList = new SelectList(_db.Categories, "CategoryID", "Name");
            return View(feed);
        }


        [HttpPost]
        public void Delete(int id)
        {

            Feed f = _db.Feeds.Find(id);
            _db.Feeds.Remove(f);
            _db.SaveChanges();
             var model = _db.Feeds.Include(c => c.Category);

        }

        public ActionResult Edit(int id)
        {
            var cat = _db.Categories.Where(u => u.UserId == userId);
            ViewBag.CategoryList = new SelectList(cat, "CategoryID", "Name");
            

Views/Shared/_FeedList.cshtml
@using LinqGrouping.Models
@model List<Group<DotNetReader.Models.FeedListItems, String>>



<hr />
<ul class="nav nav-list">

        <li><a href="@Url.Action("Views", "Feed", new { slug = "All" })"><i class="icon-fire"></i><strong>
             All items (@Model.Sum(x => x.Values.Sum(s => s.NewItemsCount)))
                                                
            
             </strong></a></li>
        <li><a href="@Url.Action("Views", "Feed", new { slug = "Star" })"><i class="icon-star"></i> Starred items (@Model.Sum(x => x.Values.Sum(s => s.Stared)))</a></li>
 </ul>
    <hr />
  <ul class="nav nav-list">  
@foreach (var grp in Model)
{
    var total = grp.Values.Sum(tot => tot.NewItemsCount);
    if(@grp.Key == null){
      <li class="nav-header"> Uncategorized (@total)</li>
    }
       else{
          <li class="nav-header"> @grp.Key (@total)</li>
    }
    foreach (var item in grp.Values)
    {
        String link = @item.Name + " (" + @item.NewItemsCount + ")";
         <li> @Html.ActionLink(link , "View", new { id=item.Id })</li>
    }

    
    
}
</ul>
    <hr />


<p>
@using(Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) {
    @Html.AntiForgeryToken()
        <a href="javascript:document.getElementById('logoutForm').submit()"class="btn btn-Action btn-larg" >Log off</a>
    } 

</p>

    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - DotNetReader</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
 
              <style type="text/css">
              body {
                padding-top: 60px;
                padding-bottom: 40px;
              }
              .sidebar-nav {
                padding: 9px 0;
              }

                  @@media (max-width: 980px)
                  {
                      /* Enable use of floated navbar text */
                      .navbar-text.pull-right
                      {
                          float: none;
                          padding-left: 5px;
                          padding-right: 5px;
                      }
                  }
        </style>
        @Styles.Render("~/Content/bootstrap")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        
            @Html.ActionLink("DotNetReader","Index","Home",null, new { @class= "brand"})
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
            @Html.Partial("_LoginPartial")
            </p>
            <ul class="nav">
              <li class="active">@Html.ActionLink("Home","Index","Home")</li>

            @if(User.Identity.IsAuthenticated){
              <li>@Html.ActionLink("Feed","Index","Feed")</li>
               <li>@Html.ActionLink("Category","Index","Category")</li>
              <li>@Html.ActionLink("Manage Account","Manage","Account")</li>
            }
               @if(User.IsInRole("Admin")){
                 <li>@Html.ActionLink("Administration Panel","Index","Admin")</li> 
              }
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid"> <!-- ICI C LES CHOSES QUI SE PASSENT -->
   

         <div class="row-fluid">
        <div class="span2" >
               <div data-spy="affix">
            @if (Request.IsAuthenticated) {
                <p><a class="btn btn-large" href="@Url.Action("UpdateAll","Feed")"><i class="icon-refresh"></i> Update</a></p>
                <div id="content-feed">
              @Html.Action("ListFeed","Feed")
                    </div>
            }
                   </div>
        </div>
        <div class="span10">
          
         @RenderBody()
        </div>
        </div>

    </div><!--/.fluid-container-->

    </body>
     @Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/bootstrap")
     @RenderSection("scripts", required: false)
</html>
 





        
     

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - DotNetReader</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
 
          
        @Styles.Render("~/Content/bootstrap")
        @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
  </head>

  <body>

    <div class="container">
    @RenderBody()

    </div> <!-- /container -->

    </body>
        @Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</html>
 





        
     

Views/Shared/_PartialManageFeed.cshtml
@model IEnumerable<DotNetReader.Models.Feed>

<div id="content-anus">
<div class="row">
    <div class="span10 offset1">
        <h2>List of feeds</h2>

<p>
       @Html.ActionLink("Add New", "Create",null, new { @class= "btn"})
</p> 

<table class="table">
    <tr>
         <th>
            @Html.DisplayNameFor(model => model.Lastupdate)
        </th>
        <th>
           Feeds    
        </th> 
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>

        <th>Update</th>
    </tr>

@foreach (var item in Model) {
    <tr>
                <td>
            @Html.DisplayFor(modelItem => item.Lastupdate)
        </td>
        <td>
            <p> <a href="@item.Website">@item.Name</a><br />
            <em> @Html.DisplayFor(modelItem => item.Description)</em><br />

                  <small>@item.Url</small>

            </p>
        </td>
                <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.FeedID })

            <a href="javascript:void(0)" id="@item.FeedID" class="confirmLink">Delete</a>
        </td>
    </tr>
}

</table>
 </div>
</div>

    </div>